added lunarbasemission1~4 and corrected mistake
wb1016/sb_korpatch pull request #29
Opened 2021-06-06 11:32 UTC by OABHs

하이로틀 미션 코덱스 7번의 내용이 코덱스 UI를 벗어나는 것을 추가로 고쳤습니다.

2021-06-06 17:42 UTC, wb1016 commented on codex/missions/hylotl mission/competition winners/hylotlmission7.codex.patch
>  \uBE5B\uC740 \uB179\uC0C9\uC73C\uB85C \uBE5B\uB098\uACE0, \uB098\uB294 \uC2DC\uAC04\uC744 \uB0AD\uBE44\uD558\uC9C0 \uC54A\uC73C\uBA70-
_Ship is prepped, I hear it humming,_ 
워프 드라이브 이야기를 하는 것으로 보아 여기서 ship은 배가 아니라 함선(우주선) 으로 보입니다.

빛은 녹색으로 빛나고, 나는 시간을 낭비하지 않으며-
영어에는 dash가 문장부호로 작용하지만, 국어에는 dash가 존재하지 않습니다.

2021-06-06 17:43 UTC, wb1016 commented on codex/missions/hylotl mission/competition winners/hylotlmission7.codex.patch
>  \uC18D\uB825\uC744 \uCD5C\uB300\uB85C \uB192\uC774\uACE0, \uBC94\uD589\uC744 \uC800\uC9C0\uB978\uB2E4.
속력보다는 쓰로틀 또는 스로틀 그대로 음차하는 것이 맞다고 생각됩니다. 또는 출력을 높인다는 표현도 가능합니다.

2021-06-06 18:03 UTC, wb1016 requested changes
코덱스를 여태까지 merge 하는 것에만 집중해서 검증을 제대로 하지 못했는데 이번에는 제대로 해봤습니다.

2021-06-06 18:03 UTC, wb1016 commented on codex/missions/lunar base mission/lunarmission4.codex.patch
> +\uC5D0\uB974\uD0A4\uC6B0\uC2A4 \uC0DD\uBA85\uCCB4\uAC00 \uADC0\uD558\uC758 \uC2DC\uC124\uC5D0\uC11C \uAE68\uC5B4\uB0AC\uC2B5\uB2C8\uB2E4. \uBCF8\uC0AC\uB294 \uC9C1\uC6D0\uB4E4\uC774 \uD3C9\uC815\uC74
'service' 를 음차하는 것이 아니라 노고, 수고, 근무 등으로 번역 하는것이 맞다고 생각됩니다. '서비스'를 그대로 음차하는 것은 국어에서 경의를 담는 표현이 아니기 때문입니다.

2021-06-07 15:11 UTC, OABHs commented on codex/missions/hylotl mission/competition winners/hylotlmission7.codex.patch
>  \uC18D\uB825\uC744 \uCD5C\uB300\uB85C \uB192\uC774\uACE0, \uBC94\uD589\uC744 \uC800\uC9C0\uB978\uB2E4.
throttle은 여기서 계기판을 의미하며, hit the throttle, 혹은 punch the throttle로 쓰면 문자 그대로의 의미 보다는 더 비유적으로, 속력을 (급하게, 최대로) 높이다 내지는 말씀하신 출력을 높이다 정도로 이해할 수 있습니다. 또 비슷한 표현으로는 Full-throttle이 있는데 자동차나 보트같은 탈 것의 맥락에서는 최고 속력을 의미합니다. 그래서 '속력을 최대로 높이다'라는 번역도 가능하다고 생각합니다. 또 개인적으로는, 근거가 미약하긴 하나 보통 엔진의 경우 '출력을 높이다'를 사용하고, 엔진이 아닌 탈 것의 경우에는 '속력을 높이다'가 더 자주 쓰인다고 생각합니다만, 말했다시피 제가 느끼기에 그런거라서 확실하지는 않습니다.

2021-06-07 15:34 UTC, OABHs commented
1) hylotlmission7.codex patch
 - 문법 실수를 고쳤습니다
 - throttle의 번역 이외에 지적받은 부분을 고쳤습니다
 - 기타 사소한 부분을 더 수정했습니다

2) lunarmission1, 2, 4.codex.patch
 - 지적받은 부분을 고쳤습니다
 - 한 곳 오타가  있어서 그 부분 수정했습니다

2021-06-07 16:44 UTC, wb1016 reviewed
throttle

2021-06-07 16:44 UTC, wb1016 commented on codex/missions/hylotl mission/competition winners/hylotlmission7.codex.patch
>  \uC18D\uB825\uC744 \uCD5C\uB300\uB85C \uB192\uC774\uACE0, \uBC94\uD589\uC744 \uC800\uC9C0\uB978\uB2E4.
throttle은 모든 종류의 기계에서 출력을 조정하는 장치 또는 인터페이스를 이야기합니다. 일례로 육군 트럭에는 사보타주 공격을 위한 스로틀 레버가 있습니다. 하지만 스로틀은 속력과 비례하지 않습니다. 대부분의 경우 손상을 방지하기 위해 최대 속력을 지켜야 하기 때문입니다. 또 예시를 들자면, space shuttle의 RS-25 SSME는 점화 시 약 80% throttle로 시작하고, 서서히 증가합니다. T+1m 정도에 100%까지 올라가고, 이후 thrust/weight ratio를 유지하기 위해 계속 감소합니다. 최종적으로 마무리 단계, 즉 가장 빠를 때는 60%까지 감소합니다. 이렇듯 속력과는 큰 관계가 없습니다.

2021-06-07 16:44 UTC, wb1016 commented on codex/missions/hylotl mission/competition winners/hylotlmission7.codex.patch
> +  "op": "add",
이건 왜 add인가요?

2021-06-07 17:11 UTC, OABHs commented on codex/missions/hylotl mission/competition winners/hylotlmission7.codex.patch
> +  "op": "add",
해당 부분을 add로 한 까닭은, 본래 코덱스는 1페이지 짜리 코덱스였는데, 한글로 작성하니 내용이 코덱스 UI를 넘어가 버려서 어쩔 수 없이 2페이지로 나누었기 때문입니다. 그때 실수로 add가 아니라 replace로 올렸었는데 그걸 고친 겁니다.

2021-06-07 17:17 UTC, OABHs commented on codex/missions/hylotl mission/competition winners/hylotlmission7.codex.patch
> +  "op": "add",
> throttle은 모든 종류의 기계에서 출력을 조정하는 장치 또는 인터페이스를 이야기합니다.
이 단어가 말씀하신 장치를 의미하는 것은 압니다만, punch the throttle이 주는 비유적인 의미에 집중한 것입니다. 

해당 화자가 주먹을 꽉 쥐고 속도계 내지는 계기판을 친 것이 아니라, 해당 장치에서 눈금을 가리키는 침이 한순간에 최대치로 높아졌다는 것을 표현했다는 점에 주목했습니다. 단어의 본뜻이 아니라, 표현의 의미를 중요하게 여긴 것이죠.

 다만 쓰로틀에서 표시되는 수치가 높은 것이 무조건 속력에 비례하지는 않는다는 것은 이해하였습니다. 나중에 출력으로 고쳐서 올리겠니다.

2021-06-07 18:01 UTC, wb1016 approved these changes

2021-06-07 18:04 UTC, merged