added some radiomessages and cinematic files
wb1016/sb_korpatch pull request #49
Opened 2022-07-25 18:20 UTC by OABHs

다음 파일들은 스타바운드 인트로에서 나오는 컷신과 라디오메시지의 번역입니다.
introstage.cinematic.patch
introstart.cinematic.patch
intro.radiomessages.patch

다음은 첫 행성의 퀘스트에서 나오는 라디오메시지의 번역입니다.
quests.radiomessages.patch

다음은 각각 함선 승무원 관련 라디오 메시지와 테크 코스 관련 라디오 메시지의 번역입니다.
ship.radiomessages.patch
techchallenge.radiomessages.patch

다음은 첫행성 튜토리얼(각종 아이템 첫 입수 시 설명, 배고픔 설명 등등)과 피스키퍼 미션 튜토리얼에서 나오는 라디오메시지의 번역입니다.
tutorial.radiomessages.patch

다음은 에스더 첫 조우시 나오는 컷신의 번역입니다. 추후에 번역 수정할 가능성 높은 친구입니다.
esther.cinematic.patch

2022-07-26 05:25 UTC, wb1016 commented on radiomessages/tutorial.radiomessages.patch
> +  "value": "\uC528\uC557\uC744 \uBC1C\uACAC\uD558\uC2E0 \uAC83\uC73C\uB85C \uBCF4\uC774\uB294\uAD70\uC694. \uACBD\uC791\uB41C \uD1A0\uC591\uC5D0 \uC2EC\uACE0, \uC528\uC557\uC774 \uC790\uB77C\uB0A0 \u
"수렵용품 제작대"가 알맞은 표현같지는 않지만, 원문 뜻과 같으므로 지금은 넘어가고 알맞은 의역 제안을 받아보겠습니다.

2022-07-26 06:01 UTC, wb1016 commented on radiomessages/techchallenge.radiomessages.patch
> +  "value": "\uC6D0\uACA9\uCE21\uC815\uAE30\uC5D0 \uB530\uB974\uBA74 \uC800 \uAC70\uB9AC\uB97C \uB6F0\uC5B4 \uB118\uAE30 \uC704\uD574\uC120 \uBAA9\uD45C \uD50C\uB7AB\uD3FC\uC758 \uBAA8\uC11C\uB9AC\uC6
"원격측정기에"->"원격 측정기에"

2022-07-26 06:21 UTC, wb1016 requested changes
esther.cinematic.patch는 띄어쓰기 교정이 조금 필요해 보이며, 'Ancient'의 번역명은 이미 '고대인'으로 협의되었으나 ( #5 ) 다시 협의할 필요가 있어보입니다,

2022-07-26 06:21 UTC, wb1016 commented on radiomessages/techchallenge.radiomessages.patch
> +  "value": "^#71f2f6;F\uB97C \uB20C\uB7EC ^orange;\uB514\uC2A4\uD1A0\uC158 \uC2A4\uD53C\uC5B4 \uD14C\uD06C^white;\uB97C \uAD6C\uC0AC\uD558\uC5EC \uC555\uCD95\uB41C \uD615\uD0DC\uB85C \uBCC0\uC2E0\uD5
"디스토션 스피어"는 의역할 필요가 있어 보입니다. #51 을 확인해주세요.

2022-07-26 06:21 UTC, wb1016 commented on radiomessages/quests.radiomessages.patch
> +  "value": "\uAC00\uAE4C\uC774\uC5D0 \uC788\uB294 ^orange;\uD589\uC131 \uD575 \uD30C\uD3B8^reset;\uC744 \uC0B4\uD3B4\uBD24\uC2B5\uB2C8\uB2E4. \uD30C\uD3B8\uB4E4\uC740 \uC774 \uD589\uC131\uC758 \uC9C0
"광물군집"->"광물 군집"

2022-07-26 06:21 UTC, wb1016 commented on radiomessages/intro.radiomessages.patch
> +  "value": "\uB300 \uC218\uD638\uC790\uB2D8\uC774 \uB5A8\uC5B4\uD2B8\uB9AC\uC2E0 \uBB3C\uC9C8 \uC870\uC791\uAE30\uB97C \uAC00\uC838\uAC00\uC694! \uC0B4\uC544\uB0A8\uB294\uB370 \uD544\uC218\uC801\uC77
"가져가요"->"가져가세요"
(어체 통일)

2022-07-26 06:21 UTC, wb1016 commented on radiomessages/intro.radiomessages.patch
> +  "value": "\uCC9C\uC7A5\uC774 \uBB34\uB108\uC9C4 \uAC83 \uCC98\uB7FC \uBCF4\uC774\uB294\uAD70\uC694. \uBB3C\uC9C8 \uC870\uC791\uAE30\uB97C \uC0AC\uC6A9\uD574 \uC774 \uD759\uC744 \uCE58\uC6B8 \uC218
"꾹 클릭해"->"길게 클릭해"

2022-07-26 06:21 UTC, wb1016 commented on radiomessages/intro.radiomessages.patch
> +  "value": "\uC774 \uAC19\uC740 \uBC1C\uD310\uC5D0\uC11C \uB6F0\uC5B4\uB0B4\uB9AC\uB824\uBA74 ^#71f2f6;S\uB97C \uAFB9 \uB20C\uB7EC \uC6C5\uD06C\uB9B0 \uB2E4\uC74C \uC2A4\uD398\uC774\uC2A4 \uBC14\uB97
"꾹 눌러"->"길게 눌러"

2022-07-27 08:24 UTC, OABHs commented
> 

디스코드에도 말씀드렸는데 혹시몰라 여기도 적어두겠습니다. 원문이 the Ancient가 아니라 the Cultivator여서 경작자로 번역한 거라서 Ancient와는 별개의 번역입니다.

2022-07-28 04:52 UTC, merged